name: F-Droid nightly builds
description: Create and deploy Android app nightly builds
branding:
  icon: package
  color: green
inputs:
  debug_keystore:
    description: Your debug keystore
    required: true
  fdroid_nightly_args:
    description: Additional args to the fdroid nightly command
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.fdroid_nightly_args }}
  env:
    DEBUG_KEYSTORE: ${{ inputs.debug_keystore }}